### ISSUE TITLE
Restrict the location of clade MRCAs

### ISSUE THREAD

**Issue by sbenvari** [CompEvol/beast2#1193]
Hi,

In continuous phylogeography, in this URL it is mentioned that: https://www.beast2.org/2022/03/01/phylogeography.html
_"Also, it is possible to add priors that restrict the location of clade MRCAs, like the root location of the tree, by defining a region in KML._"

However, I couldn't find any instructions on how to do this anywhere. Could you please provide help?

I have generated a KML file that includes only terrestrial areas, excluding oceans, and I would like to use it to constrain ancestral locations.

Thank you!

**Comment by rbouckaert** [comment]
https://www.beast2.org/2019/11/21/geography-priors.html describes how to set up geographical priors, though it may be a bit out of data -- let me know if it does not work any more.

**Comment by sbenvari** [comment]
Thank you for your reply. I updated my XML file as instructed, but encountered an error:

```
Loading package BEAST_CLASSIC v1.6.3 ORC v1.2.0 BEAST.app v2.7.7 BEAST.base v2.7.7 BEASTLabs v2.0.2

Error 1017 parsing the xml input file

Class could not be found. Did you mean beastclassic.continuous.SampledMultivariateTraitLikelihood?
Perhaps a package required for this class is not installed?

Error detected about here:
  <beast>
      <run id='mcmc' spec='MCMC'>
          <distribution id='posterior' spec='CompoundDistribution'>
              <distribution id='likelihood' spec='CompoundDistribution'>
                  <distribution id='locationtreeLikelihood.geo' spec='sphericalGeo.ApproxMultivariateTraitLikelihood'>
```

**Comment by rbouckaert** [comment]
It looks like the GEO_SPHERE package is missing.
Once you [install that package](https://www.beast2.org/managing-packages/) BEAST should be able to run the XML.
Let me know if you still run into trouble.

**Comment by sbenvari** [comment]
Thank you for your help. I installed GEO_SPHERE and ran the analysis without any errors. However, when I view the output KML file in Google Earth, I still see some origins appearing in the ocean. I'm not sure what is causing this issue.

**Comment by sbenvari** [comment]
I added an extra attribute, "isInside," to my geoprior, so it now looks like this:

```
<geoprior location='@location.s:geo' tree='@Tree.t:st1193_core' region='@terrain' isInside="true"> 
	<taxonset id='all.taxa' spec='TaxonSet' alignment='@st1193_core'/> 
</geoprior> 
```

If I want to restrict the internal nodes, is this geoprior correct?

**Comment by rbouckaert** [comment]
That is indeed expected: the geoprior specifies a taxonset and the prior applies to the location of the MRCA of the clade containing all taxa. If you use `allInternalNodes='true'` on the geoprior, the prior will be applied to all internal nodes. Perhaps that is that what you were looking for?

**Comment by sbenvari** [comment]
This is exactly what I'm looking for, but when I add this parameter to my geoprior, I get the error below. If I don't use it, the program runs without any errors.

```
location of null already set at 32.745009059517194,13.579993653730204
location of null already set at 17.032538154338756,58.71500959549548
location of null already set at 47.095034921760224,-57.43496752519404
location of null already set at 32.0637439485422,0.6400402254479007
location of null already set at 17.323037338080063,27.874045092718273
location of null already set at 26.464958034440283,54.30999912800084
location of null already set at 21.893967200622765,41.09202149106155
location of null already set at 31.156953685345055,18.69603556871384
location of null already set at 23.698459861459895,-21.417002025989504
location of null already set at 18.734233796972013,39.55650534623763
location of null already set at 30.249985700538687,60.790026583191086
location of null already set at 24.492135683867637,50.17327278057189
location of null already set at 29.937671714331348,-2.6955567142960546
location of null already set at 50.15999952028568,-42.405004091960045
location of null already set at 40.04886150035852,-22.550288071689465
location of null already set at 23.006174095386125,20.15317151636458
location of null already set at 30.803136013730306,-35.02343479844007
location of null already set at 41.27655210554277,-18.141742958306676
location of null already set at 40.18828855651089,49.5240848258321
location of null already set at 6.8041927105951805,85.76207319469849
location of null already set at -7.992907929038727,114.9160077092408
location of null already set at 8.770002865705617,38.84998790856717
location of null already set at -7.009957166632615,91.45998960997615
location of null already set at -14.89994082142317,117.76499523457892
location of null already set at -11.44646047908774,116.34047596459908
-1!=152
Something went wrong in a calculation of slocationtreeLikelihood.geo
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at sphericalGeo.ApproxMultivariateTraitLikelihood.sanitycheck(Unknown Source)
        at sphericalGeo.ApproxMultivariateTraitLikelihood.calculateLogP(Unknown Source)
        at beast.core.util.CompoundDistribution$CoreRunnable.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by rbouckaert** [comment]
Not immediately sure what causes the problem from the error message alone -- could you send the XML so I can investigate it further?

**Comment by sbenvari** [comment]
Please find my XML file attached (renamed to .txt to allow upload). I really appreciate your help!

[st1193-beast.xml.txt](https://github.com/user-attachments/files/20437076/st1193-beast.xml.txt)

**Comment by rbouckaert** [comment]
Thanks -- I converted it to BEAST v2.7 since the file was for v2.6, but that gives the same problem. It looks like a bug in the code that is trying to do a sanity check where it should not do so. Will let you know once things are fixed.

**Comment by rbouckaert** [comment]
@sbenvari tried to fix it, but no luck so far -- hope to get it done by next week.

**Comment by sbenvari** [comment]
@rbouckaert Thank you for the update!

**Comment by rbouckaert** [comment]
@sbenvari I believe the problem is fixed with a bug fix in GEO_SPHERE and the XML attached (let me know if you want me to remove it). To run this, you need BEAST v2.7 + the latest GEO_SPHERE package (v1.4.2). Let me know if you still run into any problems.

[st1193-beast2.7.xml.txt](https://github.com/user-attachments/files/20543140/st1193-beast2.7.xml.txt)

**Comment by sbenvari** [comment]
Thank you for the bug fix. It works only when the burnin is 0, if I change it to 3 milion unfortunately it wont work. Yes, I’d appreciate it if you could remove the XML file.

Here is the error I received:

```
Please wait while BEAST takes 3000000 pre-burnin samples
java.lang.RuntimeException: Encountered a positive infinite posterior. This is a sign there may be numeric instability in the model.
        at beast.base.inference.MCMC.doLoop(Unknown Source)
        at beast.base.inference.MCMC.run(Unknown Source)
        at beastfx.app.beast.BeastMCMC.run(Unknown Source)
        at beastfx.app.beast.BeastMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at beast.pkgmgmt.launcher.BeastLauncher.run(Unknown Source)
        at beast.pkgmgmt.launcher.BeastLauncher.main(Unknown Source)
```

**Comment by rbouckaert** [comment]
Thanks for letting me know -- a quick fix is to just run without pre-burnin, and remove the burn-in in post-processing the output files. I'll have a closer look at what is causing the problem with pre-burnin and let you know.

**Comment by sbenvari** [comment]
@rbouckaert I changed the fill from 0 to 1 in my KML file, and it resolved the issue. Thanks a lot.

**Comment by sbenvari** [comment]
@rbouckaert I believe that editing the KML did not resolve the issue. In some runs, internal nodes remain densely concentrated in the ocean, while in others they do not. This seems to result from the inherent stochastic nature of the system. I would appreciate any thoughts you might have on this.

**Comment by sbenvari** [comment]
Thank you for your insight. I ran seven chains, and only one converged differently — it had some low ESS values but was the only run where internal nodes remained within the land constraint. To improve ESS, I would need more runs like this one. However, most runs remain in the wrong area and never fit the constraint. Interestingly, those invalid runs tend to have better ESS values. Please find attached a screenshot from Tracer showing the combined results of all seven runs. Should I keep repeating runs to get what I need, or is there anything else I can do?

![Image](https://github.com/user-attachments/assets/3763c0f6-96d0-478c-8b36-58219119e533)
